name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies
      run: |
        dotnet add ./GreenHealth-API-backend/ package Microsoft.EntityFrameworkCore --version 5.0.13
        dotnet add ./GreenHealth-API-backend/ package Microsoft.VisualStudio.Azure.Containers.Tools.Targets --version 1.10.9
        dotnet add ./GreenHealth-API-backend/ package Azure.Storage.Blobs --version 12.10.1
        dotnet add ./GreenHealth-API-backend/ package Swashbuckle.AspNetCore --version 5.6.3
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
